trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: pluto00.azurecr.io
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: docker-dotnet
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 10c569b3-cd61-4255-9d30-93cade7e263f
        tags: |
          $(tag)