trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Pay-As-You-Go(10c569b3-cd61-4255-9d30-93cade7e263f)'
        azureContainerRegistry: '{"loginServer":"pluto00.azurecr.io", "id" : "/subscriptions/10c569b3-cd61-4255-9d30-93cade7e263f/resourceGroups/pluto-redish_group/providers/Microsoft.ContainerRegistry/registries/pluto00"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        includeLatestTag: true
